### ISSUE TITLE
`release.py`: 2 pull requests associated with a commit, but in reality only one is.

### ISSUE THREAD

**Issue by thozza** [osbuild/maintainer-tools#57]
While I was doing an osbuild release, I got the following error from `release.py`:
```
...
Info: Found 16 commits since v44 in main:
26a250ca6ef4e5abef16826768e19562e4eaf602
ee96b11faf29c1fa52d919ff7b2ab5424daee5a6
d4f275e024f08ba9dd61381825e875d560cd6c35
7a2b8ac10797e42fb53caed09d7bf4ea377e4da7
94e9f62f63ea4402c884e4ce64382601f6e45a8f
e3515caf01c41cdd994cf728b8a53e823fb90067
3d4be5f05900dc4c19081f29e40c57ef46b87182
97202e53b08f62b10f843d7092afae6d00a7ede1
dccbfb591689c4c7e04f2f652bbda741b68f766b
0b8dbd4bc3ea80c66a1981cf7d44f02b2b9a9f96
fe379b631b1cc2e814a67a2961fba032a4cffc85
a9e1070ce2712eee45180ed82c5f16e8510e22bc
0cbd7898c7822d1e6c667f2376bd06fea901a71e
9786d1f0d62bbf1265b9dc03ba599db64143641d
e97f6ef34e6f8efeccae491f55ad12a0167e6015
bf3c80372a26d958d2971786e46df8fe0a6060f1
Fetching PR 1
Fetching PR 2
Fetching PR 3
Fetching PR 4
Fetching PR 5
Fetching PR 6
Fetching PR 7
Fetching PR 8
Fetching PR 9
Fetching PR 10
Fetching PR 11
Fetching PR 12
Info: There are 2 pull requests associated with a9e1070ce2712eee45180ed82c5f16e8510e22bc - skipping...
Info: https://github.com/osbuild/osbuild/pull/940
Info: https://github.com/osbuild/osbuild/pull/941
Fetching PR 13
Fetching PR 14
Fetching PR 15
Fetching PR 16
...
```

However when I checked the commit https://github.com/osbuild/osbuild/commit/a9e1070ce2712eee45180ed82c5f16e8510e22bc it seems to have only one PR associated with it, the 940.

This may be caused by a different data which were returned by GitHub API, than what is shown in the Web UI, but I didn't investigate it further.

(CC @ochosi )

**Comment by ochosi** [comment]
@thozza The unfortunate explanation is that the API is not very 'accurate', meaning that even every comment in a PR that mentions a commit is also returned. So if you comment on the changes of a PR and add a reference to a commit the GitHub API will return this commit in addition to all the commits actually contained in the PR.

Unfortunately there doesn't seem to be an API that only returns the commits that are actually being proposed in a PR...

For this specific case I looked and I'm not even sure why both PRs are returned, maybe some rebasing..?
This is the query I'm using: https://github.com/osbuild/osbuild/issues?q=a9e1070ce2712eee45180ed82c5f16e8510e22bc+is%3Aclosed

**Comment by thozza** [comment]
huh, that is weird 🤔  Since Github is rebasing and thus changing the commit SHA when merging a PR, I don't have any idea how to workaround this issue....

Maybe just one thing could be improved from my PoV - If this situation happens, stop the script after it checked all commits, before running the `git tag ...` command and continue manually. Otherwise one does not have an easy way to get back to the list of problematic commits and PRs, since their editor is already opened with the tag commit message.

**Comment by ochosi** [comment]
Tbh I didn't want to overcomplicate things and make the process too manual again.
So far this has never been a practical problem because most PRs contain >1 commit, so they will be caught with one of the commits (after all I'm going through commits and matching them to PRs, not the other way round).

As this is only about missing a PR title, I could also print the debug stuff into the tag message (git merge conflict style) and then let the user resolve it there. Thoughts?

**Comment by thozza** [comment]
> Tbh I didn't want to overcomplicate things and make the process too manual again. So far this has never been a practical problem because most PRs contain >1 commit, so they will be caught with one of the commits (after all I'm going through commits and matching them to PRs, not the other way round).

I meant that the "pause" and manual continue step would happen only in case this particular situation happens - one commit appears in two PRs and as a result, none of their summaries is added to the tag message.

> As this is only about missing a PR title, I could also print the debug stuff into the tag message (git merge conflict style) and then let the user resolve it there. Thoughts?

Yes, IMO that would work well.

The main issue from my point of view is that the tag message is missing any information about which commit and PRs were problematic. While this is shown in the log as the script is running, it may be shown just for a split second before the editor with tag message is opened.

**Comment by ochosi** [comment]
As the script is not in use anymore but instead this process is carried out by our bot I'm closing this issue.
